[package]
name = "subcli"
description = "Component Generation Tool for FRAME Pallets in the Substrate Framework"
authors = ["SubCli Team"]
version = "1.0.6"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/SubCli/cli"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"

clap = { version = "4.1.0", features = ["derive", "string"] }
string-builder = "0.2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
proc-macro2 = "1.0.67"
quote = "1.0.33"
syn = { version = "2.0.37", features = ["full","visit-mut"] }
cargo-generate = "0.18.3"
reqwest = "0.11"
tokio = { version = "1.25.2", features = ["full"] }
zip = "0.6"
convert_case = "0.6.0"
log = "0.4.20"
env_logger = "0.10.1"
prettyplease = "0.2.15"
